version: '3.6'
services:
  wsock:
    build: 
      context: nodes
      dockerfile: DockerfileN
    restart: always
    volumes:
      - ./:/external/
    entrypoint: ["/bin/bash","-c","/external/init.sh"]
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --ISCAgent false
    restart: always
    ports:
      - '51773:1972'
      - '52773:52773'
      - 53773
    volumes:
      - ./:/rcc
