version: '3.6'
services:
  wsock:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/external/
    entrypoint: ["/bin/bash","-c","/external/init.sh"]